language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

# 新版的 pip 会优先使用 wheel 而非 source 包
# 而 imageio-ffmpeg 只有 wheel 包才内嵌 ffmpeg
# 所以必须升级
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

# 必须有 script 属性，否则会有奇怪的错误。
script:
  - python -m unittest tests.test_convert

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    skip_existing: true
