language: python
python:
  - '3.6'
install:
  - pip install pipenv
  - pipenv install
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWD
  distributions: "sdist bdist_wheel"
  on:
    python: 3.6+
    tags: true
    branch: master