language: python

# this two option are required for python 3.7 currently
sudo: required
dist: xenial

python:
  - '3.6'
  - '3.7'

# 新版的 pip 会优先使用 wheel 而非 source 包
# 而 imageio-ffmpeg 只有 wheel 包才内嵌 ffmpeg
# 所以必须升级
install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv sync  #  Installs all packages specified in Pipfile.lock.

# 必须有 script 属性，否则会有奇怪的错误。
script:
  - pipenv run python -m unittest discover tests  # run all tests under module `tests`

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    skip_existing: true
    python: "3.6"  # 通用的包，只需要 deploy 一次就好
